---
on:
  push:
    branches:
      - master
  pull_request:

name: Build
jobs:
  build:
    runs-on: runs-on=${{ github.run_id }}/family=c5a.2xlarge+c6a.2xlarge/image=ubuntu24-full-x64
    name: Build
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2
      - name: Build
        run: make
