---
on:
  push:
    branches:
      - master
  pull_request:

name: Tests
jobs:
  validate:
    runs-on: self-hosted
    name: Validate
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2
      - name: Validate
        run: make validate
  test:
    runs-on: self-hosted
    name: Test
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2
      - name: Test
        run: make test
