---
on:
  push:
    branches:
      - master
  pull_request:

name: Tests
jobs:
  test:
    runs-on: runs-on=${{ github.run_id }}/family=c5a.2xlarge+c6a.2xlarge/image=ubuntu24-full-x64
    name: Test
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2
      - name: Test
        run: make test
